### ISSUE TITLE
Correct display of GST in Summary, Review and Order Summary

### ISSUE THREAD

**Issue by irab** [coshopnz/nextjs-starter-medusa#2]

**Comment by irab** [comment]
Possible workaround is setting price at $13.75 and stating product is excluding GST.

**Comment by mandyh101** [comment]
Key tasks from meeting with Ira:

/cart URL
file checkout-summary.- index.tsx

1. remove shipping section
2. taxes currently 0% but ideal: subtotal = 13.75, taxes = 2.25, total = 15 - solved for now by changing the product amount to 13.75 :D
3. see if product total price on the store page and product summary can be incl
4. remove the add gift card/discount code

**Comment by mandyh101** [comment]
Done:
- remove reference to shipping from cart and order summary
- add gift card/discount references also removed by Ira
- updated product amounts to show the GST incl amount of $15.00 - see screenshots below
- also removed reference to "variant" 

ToDo/Discuss:
- the reference to shipping, giftcards and variants is removed from the UI but there is still code referencing these features in the project, some of it just commented out incase coshop decide to use it. But to help make the code simple and easy to understand, should I work though and refactor the code we are not using out??
- for some reason when you add more than one product the product price goes from $15.00 to $14.99

**Comment by irab** [comment]
Good enough for now. Would be good to fix the $14.99 price change when ordering more than one bag
